### ISSUE TITLE
Update default content type / serving behavior for extension-less public files

### ISSUE THREAD

**Issue by jeremydw** [blinkk/rootjs#248]
**Description**

Currently, an extension-less file is served with the following content type header:

```
Content-Type:
text/html; charset=UTF-8
```

We may want to update the behavior for these to serve them as attachment (i.e. `Content-Disposition: attachment`).

This is primarily needed for files like `apple-app-site-association`. In any case, I don't think defaulting to `text/html` for these is quite correct.

Some associated discussion from Next.js about this here: https://github.com/vercel/next.js/discussions/10648

**Comment by stevenle** [comment]
I'm seeing `content-type: text/plain; charset=utf-8` returned for this, is it causing actual issues? We use `sirv` for public file serving, I can add a specific override for `apple-app-site-association` but I don't wanna create extra config options if we don't need to, esp since even next's version of it is considered experimental.

```
curl -I <domain>/.well-known/apple-app-site-association
HTTP/2 200
cache-control: max-age=3600
etag: "ee958856ed49377a9866dd541a2f764656f1c3040850ec310bf6162f628ab50a"
last-modified: Fri, 19 Jan 2024 21:59:22 GMT
strict-transport-security: max-age=31556926; includeSubDomains; preload
content-type: text/plain; charset=utf-8
```

**Comment by stevenle** [comment]
FYI Firebase Hosting has an equivalent configuration:
https://firebase.google.com/docs/hosting/full-config#headers

```
"hosting": {
  // ...

  // Applies a CORS header for all font files
  "headers": [ {
    "source": "**/*.@(eot|otf|ttf|ttc|woff|font.css)",
    "headers": [ {
      "key": "Access-Control-Allow-Origin",
      "value": "*"
    } ]
  } ]
}
```

Going to adopt their convention.
