### ISSUE TITLE
Inconsistency between `modifiedAt` and `createdAt` formats between `listDocs` and `setRawDoc`

### ISSUE THREAD

**Issue by jeremydw** [blinkk/rootjs#423]
This code snippet should explain it; it's a code snippet I've written for a project to bulk edit documents within a collection.

1. Is it possible that I'm doing something wrong between `listDocs` and `setRawDoc`?
2. Ideally `setRawDoc` would have a guard in place to check the format of the `sys` object. For example, if the `sys` object isn't structured correctly it should throw an error preventing me from writing invalid sys data to the database.

```
  const cmsClient = await getRootCMSClient();
  const {docs} = await cmsClient.listDocs('Products', {mode: 'draft'});
  for (const product of docs) {
    // Modify the "productId" field.
    if (product.fields.productId) {
      product.fields.productId = product.fields.productId.replaceAll('_', '-');
    }
    // Needed because the response of `listDocs` provides `modifiedAt` and `createdAt` as timestamps,
    // but when we write to Firestore we need to provide them as Date objects.
    product.sys.modifiedAt = new Date(product.sys.modifiedAt);
    product.sys.createdAt = new Date(product.sys.createdAt);
    await cmsClient.setRawDoc('Products', product.slug, product, {
      mode: 'draft',
    });
    console.log(`Updated product ${product.slug}`);
  }
```

**Comment by stevenle** [comment]
the createdAt / modifiedAt values should use the `Timestamp` object from `firebase-admin/firestore` when using `setRawDoc()` (`Timestamp.fromMillis(...)` is probably what you'd use). another issue is that the "set raw doc" method only works well with the "get raw doc" method since `listDocs()` won't return a "raw doc" (i.e. it'll convert arrayobjects to normal arrays)

for your purposes, i think you can use `cmsClient.saveDraftData(docId, fields)`, instead e.g.:

```
  await cmsClient.saveDraftData(`Products/${product.slug}`, product.fields);
```

**Comment by stevenle** [comment]
what i can do to make this easier is to add a `{raw: true}` option to `listDocs()`, but i think for your use case i'll suggest switching to the more user-friendly `saveDraftData()`. i'll keep this ticket open for the `{raw: true}` option but lmk if you have any issues with the suggestion above.

**Comment by jeremydw** [comment]
`saveDraftData` sounds like the correct fix for my use case. I think I have two suggestions:

1. We can update the jsdocs for `setRawDoc` to suggest using `saveDraftData` instead.
2. I think `setRawDoc` should still have some checks in place to prevent the `sys` data from being malformed (since when I incorrectly saved the doc with the wrong format for `modifiedAt`, it caused a breakage in the UI). So we can help prevent those potential consistency issues that way. Maybe this could be guarded in TS only, i.e. instead of accepting `any` for `data` we enforce the shape of the `sys` object:

https://github.com/blinkk/rootjs/blob/75e212193c853a6170cb3bb872dec18cb0149239/packages/root-cms/core/client.ts#L273

**Comment by jeremydw** [comment]
Edit: Woops, looks like the jsdocs already have the hint for `saveDraftData`. Ignore that suggestion. :)
