### ISSUE TITLE
Runtime error after building RootCMSClient in a Next.js-based project

### ISSUE THREAD

**Issue by cjwang18** [blinkk/rootjs#433]
**Describe the bug**
Ok this time I'm pretty sure it's a runtime error (only the page that instantiates the CMS client hits the error when we try to load it). I'm building our project (same one from https://github.com/blinkk/rootjs/issues/426) into a Docker image. Running a container off the image, I'm hitting this error from Vite while trying to load the page that instantiates `RootCMSClient`
```
⨯ Error: cannot test case insensitive FS, CLIENT_ENTRY does not point to an existing file: /app/node_modules/vite/dist/client/client.mjs
    at testCaseInsensitiveFS (file:///app/node_modules/vite/dist/node/chunks/dep-uAHLeuC6.js:12076:15)
    at file:///app/node_modules/vite/dist/node/chunks/dep-uAHLeuC6.js:12092:29
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:432:15)
```

I thought I could get smart about it and prevent Vite from even being accessible by configuring this in `next.config` (some documentation [here](https://nextjs.org/docs/pages/api-reference/next-config-js/output#caveats)). Next tries to trace all the dependencies required for a standalone build and this rule allows us to exclude certain things from being bundled. On the flip side, there's also one to include things if their tracing missed something.
```
outputFileTracingExcludes: {
  '/': ['./node_modules/vite/**/*'],
},
```

However, we then get the following error, which makes sense to me since there's a reference from `@blinkk/root-cms` to `@blinkk/root` to `vite` so I don't think that particular config is correct either.

```
 ⨯ Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite' imported from /app/node_modules/@blinkk/root/dist/chunk-ZQSNXUYH.js
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:916:9)
    at moduleResolve (node:internal/modules/esm/resolve:973:20)
    at defaultResolve (node:internal/modules/esm/resolve:1193:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:404:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:373:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:250:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**To Reproduce**
1. Install `@blinkk/root` and `@blinkk/root-cms` into a Next.js project
2. Create an App Router page (src/app/page.tsx) that attempts to instantiate `RootCMSClient` with the `cmsPlugin` to communicate with Firebase
3. Call `cmsClient.getDoc`
4. Configure Next to build with `output: standalone` in config
5. Set up Dockerfile to create image
6. Build the docker image based on Dockerfile
7. Run a container off the image
8. Visit the page and see error

**Expected behavior**
No error

**Screenshots**
N/A

**Additional context**
Adding `@blinkk/root` and even `vite` as `serverComponentsExternalPackages` into `next.config` does not change anything.

**Comment by stevenle** [comment]
@cjwang18 can you initialize a stackblitz project that shows the issue?

**Comment by cjwang18** [comment]
I'm not sure how helpful that would be or if it would even be reproducible. This only happens when building the project and not during dev.

I can try to get a simple repro on Github though

**Comment by cjwang18** [comment]
Ok here it is: https://github.com/cjwang18/blinkk-rootjs-433-repro

**Comment by stevenle** [comment]
@cjwang18 i think the example you gave has the RootCMSClient initiated directly in the page component, ideally the data is fetched in getStaticProps() or getServerProps() so that it's handled on the server-side. is it set up differently in your actual app? if so, can you update your example to more accurately reflect?

**Comment by cjwang18** [comment]
No the setup is the same. We're using Next's App Router, and my understanding is that these components are React Server Components and thus server-rendered by default. `getStaticProps` and `getServerSideProps` are only applicable to components using Pages Router, which we are not.

**Comment by cjwang18** [comment]
Hmm, I think I figured it out. I'll update this comment with my findings

**Comment by stevenle** [comment]
@cjwang18 ah okay gotcha. for reference, what was the config change to signal to next that the entire vite dist folder should be included?

**Comment by cjwang18** [comment]
`outputFileTracingIncludes`. Some documentation around it in the [Caveats section](https://nextjs.org/docs/app/api-reference/next-config-js/output#caveats) after the first code example
